version: '2'
services:
  cuutro:
    image: cuutro:latest
    ports:
    - "8080:8080"
    env_file:
      - staging.env
    depends_on:
      - db

  db:
    image: mongo:latest
    ports:
    - "27107:27107"
    container_name: mongo
    environment:
      MONGO_INITDB_DATABASE: cuu_tro


